services:
  webserver:
    build:
      context: .
      dockerfile: dockerfile_django
    command: >
      sh -c "python manage.py collectstatic --noinput &&
      gunicorn golden_hex_django_app.wsgi:application --bind 0.0.0.0:8000"
    volumes: 
      - static_volume:/golden_hex_django/staticfiles
    container_name: django_server
    ports:
      - "8000:8000"
    restart: always

  proxy_server:
    build:
      context: .
      dockerfile: dockerfile_nginx
    container_name: nginx_proxy
    volumes:
      - static_volume:/golden_hex_django/staticfiles
    ports:
      - "8080:80"
    depends_on:
      - webserver
    restart: always


volumes:
  static_volume:

