# Use an official Python runtime as a parent image
FROM python

# Set the working directory to /app
WORKDIR /golden_hex_django

# Copy the current directory contents into the container at /app
#COPY . /app

# Install any dependencies specified in requirements.txt
RUN apt update && apt install -y git && apt-get clean
RUN git clone https://github.com/campagnollo/golden_hex_django.git temp_repo && \
    mv temp_repo/* temp_repo/.* . 2>/dev/null || true && \
    rm -rf temp_repo
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install gunicorn && \
    python manage.py migrate


# Make port 80 available to the world outside this container
EXPOSE 8000

# Define environment variable
ENV NAME=django_golden_hex2

# Run app.py when the container launches
CMD ["python", "golden_hex_django/manage.py", "runserver", "0.0.0.0:8000"]

