
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile_django
    volumes: 
      - ./static:/golden_hex_django/myapp/static
    container_name: django_app
    ports:
      - "8000:8000"
    restart: always

  proxy_server:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    container_name: nginx_proxy
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./golden_hex_django/staticfiles:/test_golden_hex_django/golden_hex_django/staticfiles:ro
    ports:
      - "8080:80"
    depends_on:
      - webserver
    restart: always

